# Generated by Django 3.1.1 on 2020-09-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapackagestatus',
            name='behaviour',
            field=models.CharField(choices=[('CREATION', 'Default on Creation')], default='CREATION', max_length=9),
        ),
    ]
