# Generated by Django 3.1.1 on 2020-09-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datapackagestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapackagestatus',
            options={'verbose_name_plural': 'Datapackage statuses'},
        ),
        migrations.AddField(
            model_name='datapackage',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.datapackagestatus'),
        ),
    ]
