# Generated by Django 3.1.1 on 2020-09-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datapackagestatus_behaviour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapackagestatus',
            name='behaviour',
            field=models.CharField(blank=True, choices=[('CREATION', 'Default on Creation')], max_length=9, null=True),
        ),
    ]
