# Generated by Django 3.1 on 2020-08-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_create_modify_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='schema',
            field=models.TextField(),
        ),
    ]
