# Generated by Django 3.1 on 2020-08-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='collaborator',
            field=models.ManyToManyField(to='core.Person'),
        ),
        migrations.AddField(
            model_name='schema',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
