# Generated by Django 3.1.2 on 2020-11-04 14:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_status_can_be_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapackage',
            name='status',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.datapackagestatus'),
        ),
        migrations.AlterField(
            model_name='datapackage',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
