# Generated by Django 3.1 on 2020-08-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_collaborator_and_name_to_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.RenameField(
            model_name='schema',
            old_name='collaborator',
            new_name='collaborators',
        ),
    ]
