# Generated by Django 3.1.1 on 2020-09-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200908_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapackagestatus',
            name='name',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
