# Generated by Django 3.1 on 2020-08-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_rename_collaborator_to_collaborators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='schema',
            old_name='full_name',
            new_name='name',
        ),
    ]
