# Generated by Django 3.1 on 2020-08-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fixes_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to='core.Person'),
        ),
    ]
