# Generated by Django 3.1 on 2020-08-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_collaborators_can_be_empty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schema',
            new_name='Datapackage',
        ),
    ]
