# Generated by Django 3.1.2 on 2020-10-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
